import '../css/app.css'
import './bootstrap'

import { createInertiaApp } from '@inertiajs/vue3'
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers'
// Cache bust: Company translations loaded - 2025-10-16 16:45:00
import { createApp, h } from 'vue'
import { ZiggyVue } from '../../vendor/tightenco/ziggy'
import { createI18n } from 'vue-i18n'

const appName = import.meta.env.VITE_APP_NAME || 'Laravel'

// Sync LocalStorage locale preference to cookie (so server can read it)
// This is better than using cookies for storage because:
// 1. LocalStorage doesn't send data with every request (better performance)
// 2. We only use the cookie to pass the value to the server
// 3. Primary storage is still LocalStorage (browser-side)
if (typeof window !== 'undefined' && window.localStorage) {
    const preferredLocale = window.localStorage.getItem('preferred_locale')
    if (preferredLocale) {
        // Set cookie with 1 year expiry
        document.cookie = `preferred_locale=${preferredLocale}; path=/; max-age=31536000; SameSite=Lax`
    }
}

// I18n messages
const messages = {
    en: {
        auth: {
            email: 'Email Address',
            enter_email: 'Enter your email',
            continue: 'Continue',
            welcome_back: 'Welcome back!',
            new_here: "New here? We'll create your account.",
            login: 'Login',
            register: 'Register',
            password: 'Password',
            remember_me: 'Remember me',
            forgot_password: 'Forgot your password?',
            secure_auth: `Secure authentication powered by ${appName}`,
            forgot_password_title: 'Forgot Password',
            forgot_password_description:
                "Forgot your password? No problem.\nEnter your email below, and we'll send you a link to reset it securely.",
            email_password_reset_link: 'Email Password Reset Link',
            reset: 'Reset',
            back: 'Back',
            back_to_login: 'Back to Login',
            remember_password: 'Remember your password?',
        },
        errors: {
            page_not_found: 'Page Not Found',
            page_not_found_description:
                'Sorry, the page you are looking for could not be found.',
            server_error: 'Server Error',
            server_error_description:
                'Something went wrong on our end. Please try again later.',
            forbidden: 'Access Forbidden',
            forbidden_description:
                'You do not have permission to access this resource.',
            csrf_mismatch: 'Session Expired',
            csrf_mismatch_description:
                'Your session has expired. Please refresh the page and try again.',
            go_home: 'Go Home',
            try_again: 'Try Again',
            go_back: 'Go Back',
            refresh_page: 'Refresh Page',
            need_help: 'Need help? Contact our support team.',
            contact_support: 'Contact Support',
            error_404: '404 - Page Not Found',
            error_500: '500 - Server Error',
            error_403: '403 - Access Forbidden',
            error_419: '419 - Session Expired',
        },
        dashboard: {
            title: 'Dashboard',
            greeting_morning: 'Good morning',
            greeting_afternoon: 'Good afternoon',
            greeting_evening: 'Good evening',
            welcome_messages: [
                `Welcome to ${appName}. Let's make something amazing today.`,
                "Ready to automate your social media? Let's get started!",
                "Your content deserves to shine. Let's make it happen.",
                'Time to turn your ideas into engaging posts.',
                'Great content starts here. What will you create today?',
                "Let's grow your Instagram presence together.",
                'Welcome back! Your audience is waiting for your next post.',
            ],
            instagram_accounts: 'Instagram Accounts',
            scheduled_posts: 'Scheduled Posts',
            wallet_balance: 'Wallet Balance',
            connect_instagram: 'Connect Instagram',
            connect_instagram_desc:
                'Link your Instagram account to start automating your content.',
            connect_now: 'Connect Now',
            actions: {
                create_post: 'Create Post',
                create_post_desc:
                    'Schedule and publish content across your Instagram accounts.',
                coming_soon: 'COMING SOON',
            },
            empty_state: {
                no_posts: 'No posts yet',
                get_started: 'Get started by creating your first post',
            },
            recent_posts: 'Recent Posts',
            view_all_posts: 'View all posts',
        },
        posts: {
            create_post: 'Create Post',
            back_to_posts: 'Back to Posts',
            select_post_type: 'Select Post Type',
            select_post_type_description:
                'Choose the type of content you want to create',
            select_instagram_account: 'Select Instagram Account',
            select_instagram_account_description:
                'Choose which Instagram account to post to',
            select_account: 'Select Account',
            post_details: 'Post Details',
            title: 'Post Management',
            optional: 'Optional',
            title_placeholder: 'Enter a title for your post...',
            caption: 'Caption',
            caption_placeholder: 'Write your caption here...',
            characters: 'characters',
            status_label: 'Status',
            type_label: 'Type',
            media_upload: 'Media Upload',
            media_upload_description: 'Upload images or videos for your post',
            scheduling: 'Scheduling',
            scheduling_description: 'Choose when to publish your post',
            publish_immediately: 'Publish Immediately',
            save_draft: 'Save Draft',
            schedule_for_later: 'Schedule for Later',
            cancel: 'Cancel',
            // Scheduling Interface
            quick_select: 'Quick Select',
            custom_schedule: 'Custom Schedule',
            now: 'Now',
            today_1h: 'Today (+1 hour)',
            today_3h: 'Today (+3 hours)',
            today_6h: 'Today (+6 hours)',
            tomorrow_9am: 'Tomorrow (9:00 AM)',
            tomorrow_6pm: 'Tomorrow (6:00 PM)',
            next_week: 'Next Week',
            next_month: 'Next Month',
            select_date: 'Select Date',
            select_time: 'Select Time',
            date_placeholder: 'Choose a date',
            time_placeholder: 'Choose a time',
            scheduled_for: 'Scheduled for',
            type: {
                feed: 'Feed Post',
                feed_description: 'Regular post that appears in your feed',
                reel: 'Reel',
                reel_description: 'Short-form video content',
                story: 'Story',
                story_description:
                    'Temporary content that disappears after 24 hours',
                carousel: 'Carousel',
                carousel_description: 'Multiple images or videos in one post',
            },
            media: {
                upload: 'Upload Media',
                or_drag_drop: 'or drag and drop files here',
                supported_formats: 'Supported formats: JPG, PNG, GIF, MP4, MOV',
                add_more: 'Add more files',
                existing: 'Existing',
                duplicated: 'Duplicated',
                too_many_files: 'Too many files. Maximum {max} files allowed.',
                file_too_large:
                    'File {name} is too large. Maximum size is {max}.',
                invalid_file_type: 'File {name} has invalid type {type}.',
            },
            select_date: 'Select Date',
            select_time: 'Select Time',
            date_placeholder: 'Choose a date...',
            time_placeholder: 'Choose a time...',
            scheduled_for: 'Scheduled for',
            quick_select: 'Quick Select',
            today_6pm: 'Today 6:00 PM',
            tomorrow_9am: 'Tomorrow 9:00 AM',
            tomorrow_12pm: 'Tomorrow 12:00 PM',
            tomorrow_6pm: 'Tomorrow 6:00 PM',
            next_week: 'Next Week',
            next_month: 'Next Month',
            creating: 'Creating...',
            all_statuses: 'All Statuses',
            all_types: 'All Types',
            search_posts: 'Search posts...',
            no_posts: 'No posts found',
            no_posts_description: 'Get started by creating your first post',
            status: {
                draft: 'Draft',
                scheduled: 'Scheduled',
                publishing: 'Publishing',
                published: 'Published',
                failed: 'Failed',
            },
            stats: {
                total_posts: 'Total Posts',
            },
            created_successfully: 'Post created successfully!',
            view: 'View',
            edit: 'Edit',
            delete: 'Delete',
            duplicate: 'Duplicate',
            actions: 'Actions',
            media_count: 'Media',
            source: 'Source',
            created_at: 'Created',
            scheduled_at: 'Scheduled',
            images: 'images',
            videos: 'videos',
            no_media: 'No media',
            unknown_source: 'Unknown',
            not_scheduled: 'Not scheduled',
            untitled: 'Untitled',
            no_caption: 'No caption',
            confirm_delete: 'Are you sure you want to delete this post?',
            deleted_successfully: 'Post deleted successfully!',
            delete_failed: 'Failed to delete post.',
            no_instagram_accounts: 'No Instagram Accounts Connected',
            no_instagram_accounts_description:
                'You need to connect an Instagram account before you can create posts.',
            connect_instagram_account: 'Connect Instagram Account',
            assign_account_later: 'You can assign an Instagram account later',
            create_post_without_account:
                'You can create a post without connecting an Instagram account first',
            or: 'or',
            assign_later: 'assign later',
        },
        common: {
            view: 'View',
            edit: 'Edit',
            delete: 'Delete',
            save: 'Save',
            cancel: 'Cancel',
            back: 'Back',
            next: 'Next',
            previous: 'Previous',
            loading: 'Loading...',
            error: 'Error',
            success: 'Success',
            warning: 'Warning',
            info: 'Info',
            yes: 'Yes',
            no: 'No',
            ok: 'OK',
            close: 'Close',
            open: 'Open',
            search: 'Search',
            filter: 'Filter',
            sort: 'Sort',
            refresh: 'Refresh',
            export: 'Export',
            import: 'Import',
            download: 'Download',
            upload: 'Upload',
            select: 'Select',
            select_all: 'Select All',
            deselect_all: 'Deselect All',
            clear: 'Clear',
            reset: 'Reset',
            submit: 'Submit',
            confirm: 'Confirm',
            optional: 'Optional',
            required: 'Required',
        },
        menu: {
            dashboard: 'Dashboard',
            posts: 'Posts',
            company: 'Company',
            create_company: 'Create Company',
            profile: 'Profile',
            logout: 'Log Out',
            instagram: 'Instagram',
            instagram_accounts: 'Instagram Accounts',
            admin: 'Administration',
            inquiries: 'Inquiries',
            users: 'Users',
        },
        theme: {
            switchToDark: 'Switch to dark mode',
            switchToLight: 'Switch to light mode',
        },
        instagram: {
            title: 'Instagram Accounts',
            no_accounts: 'No Instagram accounts connected yet',
            connect_description:
                'Connect your Instagram account to start automating your content publishing.',
            connect_button: 'Connect Instagram Account',
            not_configured:
                'Instagram integration is not configured yet. Please contact your administrator to set up Instagram API credentials.',
            no_active_company:
                'You need to have an active company to connect Instagram accounts. Please create or select a company first.',
            connected: 'Connected',
            sync: 'Sync',
            disconnect: 'Disconnect',
            disconnect_confirm:
                'Are you sure you want to disconnect @{username}? You can reconnect it anytime.',
            disconnect_confirm_title: 'Disconnect Instagram Account?',
            disconnect_confirm_message:
                'Are you sure you want to disconnect {username}? You can reconnect it anytime.',
            disconnect_button: 'Yes, Disconnect',
            disconnect_cancel: 'Cancel',
            status_active: 'Active',
            status_expired: 'Expired',
            status_expiring_soon: 'Expiring Soon',
            token_warning:
                'Your access token will expire soon. Please reconnect this account to continue posting.',
        },
        company: {
            title: 'Company Information',
            description: 'Your current company and team details.',
            no_company: 'You are not currently associated with any company.',
            member_since: 'Member since',
            role_admin: 'Administrator',
            role_user: 'User',
            role_network: 'Company Admin',
            member_singular: 'Team Member',
            member_plural: 'Team Members',
            instagram_account_singular: 'Instagram Account',
            instagram_account_plural: 'Instagram Accounts',
            manage_accounts: 'Manage Instagram Accounts',

            create: {
                title: 'Create Company',
                heading: 'Create Your Company',
                description:
                    'Set up your company to start collaborating with your team.',
                name_label: 'Company Name',
                name_placeholder: 'Enter your company name',
                info_title: 'What happens next?',
                info_1: 'You will become the company administrator',
                info_2: 'You can invite team members to join',
                info_3: 'All posts will be associated with your company',
                create_button: 'Create Company',
                creating: 'Creating...',
            },

            settings: {
                title: 'Company Settings',
                company_info: 'Company Information',
                company_name: 'Company Name',
                created_at: 'Created At',
                team_members: 'Team Members',
                invite_member: 'Invite Member',
                member: 'Member',
                role: 'Role',
                joined: 'Joined',
                actions: 'Actions',
                owner: 'Owner',
                // keep role labels once only
                role_admin: 'Administrator',
                role_user: 'User',
                role_network: 'Company Admin',
                edit_role: 'Edit Role',
                remove: 'Remove',
                pending_invitations: 'Pending Invitations',
                email: 'Email',
                invited_by: 'Invited By',
                expires: 'Expires',
                resend_invitation: 'Resend Invitation',
                cancel: 'Cancel',
                update_role: 'Update Role',
                update_role_description: 'Update role for {name}',
                update: 'Update',
                invite_new_member: 'Invite New Member',
                invite_description:
                    'Send an invitation to join your company team.',
                email_placeholder: 'Enter email address',
                send_invitation: 'Send Invitation',
                confirm_remove_user:
                    'Are you sure you want to remove {name} from the company?',
                confirm_cancel_invitation:
                    'Are you sure you want to cancel the invitation to {email}?',
            },

            invitation: {
                sent: 'Invitation sent to {email}',
                resent: 'Invitation resent successfully',
                cancelled: 'Invitation cancelled successfully',
                cannot_resend_accepted: 'Cannot resend an accepted invitation.',
                title: 'Company Invitation',
                welcome_title: 'Welcome to {company_name}!',
                welcome_subtitle: 'You have been invited to join our team.',
                company_info: 'Company Information',
                company_name: 'Company Name',
                invited_by: 'Invited By',
                your_role: 'Your Role',
                email: 'Email',
                expiry_title: 'Invitation Expires',
                expiry_message: 'This invitation will expire on {expiry_date}.',
                user_not_exists_message:
                    'You need to create an account to accept this invitation.',
                footer_message:
                    'If you did not expect this invitation, you can safely ignore this email.',
                register_button: 'Create Account & Join',
            },

            toast: {
                need_company_first: 'You need to create a company first.',
                no_permission:
                    'You do not have permission to perform this action.',
                role_updated: 'User role updated successfully',
                user_removed: 'User removed from company successfully',
                login_required: 'Please log in to accept the invitation.',
                accepted:
                    'Welcome to the company! You can now access all company features.',
            },
        },
        emails: {
            company_invitation: {
                role_admin: 'Administrator',
                role_user: 'User',
                role_network: 'Company Admin',
            },
        },
        profile: {
            title: 'Profile',
            information: {
                title: 'Profile Information',
                description:
                    "Update your account's profile information and email address.",
                name: 'Name',
                email: 'Email',
                timezone: 'Timezone',
                timezone_description:
                    'All dates and times will be displayed in your selected timezone.',
                search_timezone: 'Search timezones...',
                common_timezones: 'Quick Select (USA, Canada & Key Cities)',
                all_timezones: 'All Timezones',
                unverified_email: 'Your email address is unverified.',
                resend_verification:
                    'Click here to re-send the verification email.',
                verification_sent:
                    'A new verification link has been sent to your email address.',
                save: 'Save',
                saved: 'Saved.',
            },
            password: {
                title: 'Update Password',
                description:
                    'Ensure your account is using a long, random password to stay secure.',
                current_password: 'Current Password',
                new_password: 'New Password',
                confirm_password: 'Confirm Password',
                save: 'Save',
                saved: 'Saved.',
            },
            delete: {
                title: 'Delete Account',
                description:
                    'Once your account is deleted, all of its resources and data will be permanently deleted. Before deleting your account, please download any data or information that you wish to retain.',
                button: 'Delete Account',
                confirm_title: 'Are you sure you want to delete your account?',
                confirm_description:
                    'Once your account is deleted, all of its resources and data will be permanently deleted. Please enter your password to confirm you would like to permanently delete your account.',
                password: 'Password',
                password_placeholder: 'Password',
                cancel: 'Cancel',
                confirm_button: 'Delete Account',
            },
            company: {
                title: 'Company Information',
                description: 'Your current company and team details.',
                member_since: 'Member since',
                role_admin: 'Administrator',
                role_user: 'User',
                role_network: 'Company Admin',
                member_singular: 'Team Member',
                member_plural: 'Team Members',
                instagram_account_singular: 'Instagram Account',
                instagram_account_plural: 'Instagram Accounts',
                manage_accounts: 'Manage Instagram Accounts',
            },
        },
        timezone: {
            your_timezone: 'Your Timezone',
            current_time: 'Current Time',
            click_to_change: 'Click to change timezone',
            timezone: 'Timezone',
            local_time: 'Local Time',
        },
        admin: {
            inquiries: {
                title: 'Inquiry Management',
                email: 'Email',
                ip_address: 'IP Address',
                user_agent: 'User Agent',
                created_at: 'Created At',
                delete: 'Delete',
                export: 'Export CSV',
                export_button: 'Export to CSV',
                search: 'Search by email...',
                search_placeholder: 'Search inquiries...',
                no_results: 'No inquiries found',
                total: 'Total Inquiries',
                today: 'Today',
                this_week: 'This Week',
                this_month: 'This Month',
                delete_confirm_title: 'Delete Inquiry?',
                delete_confirm_message:
                    'This action cannot be undone. The inquiry will be permanently deleted.',
                confirm_delete: 'Yes, delete it',
                cancel: 'Cancel',
                deleted_success: 'Deleted!',
                deleted_message: 'Inquiry has been deleted successfully.',
                delete_error: 'Error!',
                delete_error_message:
                    'Failed to delete inquiry. Please try again.',
                tooltip_total: 'Total number of inquiries received',
                tooltip_today: 'Inquiries received today',
                tooltip_this_week: 'Inquiries received this week',
                tooltip_this_month: 'Inquiries received this month',
            },
            users: {
                title: 'User Management',
                name: 'Name',
                email: 'Email',
                role: 'Role',
                status: 'Status',
                last_login: 'Last Login',
                stats: 'Statistics',
                actions: 'Actions',
                search: 'Search users...',
                search_placeholder: 'Search by name or email...',
                no_results: 'No users found',
                total_users: 'Total Users',
                active_users: 'Active',
                suspended_users: 'Suspended',
                new_this_month: 'New This Month',
                send_password_reset: 'Send Password Reset',
                suspend: 'Suspend User',
                unsuspend: 'Unsuspend User',
                impersonate: 'Impersonate',
                active: 'Active',
                suspended: 'Suspended',
                suspension_reason: 'Reason',
                never_logged_in: 'Never logged in',
                companies_count: 'Companies',
                instagram_accounts: 'Instagram Accounts',
                posts_count: 'Posts',
                suspend_modal_title: 'Suspend User',
                suspend_modal_message:
                    'Please provide a reason for suspension:',
                confirm_suspend: 'Suspend',
                cancel: 'Cancel',
                confirm_impersonate_title: 'Impersonate User',
                confirm_impersonate_message:
                    'You will be logged in as this user. You can stop impersonation at any time.',
                confirm_password_reset_title: 'Send Password Reset?',
                confirm_password_reset_message:
                    'A password reset link will be sent to',
                confirm_unsuspend_title: 'Unsuspend User?',
                confirm_unsuspend_message:
                    'This user will be able to log in again.',
                confirm: 'Confirm',
                success: 'Success!',
                error: 'Error!',
                password_reset_sent:
                    'Password reset link has been sent successfully',
                user_suspended: 'User has been suspended',
                user_unsuspended: 'User has been unsuspended',
                impersonation_started: 'Now impersonating user',
                action_failed: 'Failed to complete action. Please try again.',
                tooltip_total_users: 'Total number of registered users',
                tooltip_active_users: 'Users who are active and not suspended',
                tooltip_suspended_users:
                    'Users who have been suspended by admins',
                tooltip_new_this_month: 'New users registered this month',
            },
            impersonating: 'You are impersonating',
            stop_impersonation: 'Stop Impersonation',
            loading: 'Loading...',
        },
    },
    ru: {
        auth: {
            email: 'Электронная почта',
            enter_email: 'Введите вашу электронную почту',
            continue: 'Продолжить',
            welcome_back: 'С возвращением!',
            new_here: 'Новый пользователь? Мы создадим ваш аккаунт.',
            login: 'Войти',
            register: 'Регистрация',
            password: 'Пароль',
            remember_me: 'Запомнить меня',
            forgot_password: 'Забыли пароль?',
            secure_auth: `Безопасная аутентификация от ${appName}`,
            forgot_password_title: 'Забыли пароль',
            forgot_password_description:
                'Забыли пароль? Не проблема.\nВведите ваш email ниже, и мы отправим вам ссылку для безопасного сброса пароля.',
            email_password_reset_link: 'Отправить ссылку для сброса пароля',
            reset: 'Сбросить',
            back: 'Назад',
            back_to_login: 'Вернуться к входу',
            remember_password: 'Помните пароль?',
        },
        errors: {
            page_not_found: 'Страница не найдена',
            page_not_found_description:
                'Извините, запрашиваемая страница не найдена.',
            server_error: 'Ошибка сервера',
            server_error_description:
                'Произошла ошибка на нашей стороне. Пожалуйста, попробуйте позже.',
            forbidden: 'Доступ запрещен',
            forbidden_description:
                'У вас нет прав для доступа к этому ресурсу.',
            csrf_mismatch: 'Сессия истекла',
            csrf_mismatch_description:
                'Ваша сессия истекла. Пожалуйста, обновите страницу и попробуйте снова.',
            go_home: 'На главную',
            try_again: 'Попробовать снова',
            go_back: 'Назад',
            refresh_page: 'Обновить страницу',
            need_help: 'Нужна помощь? Обратитесь в службу поддержки.',
            contact_support: 'Связаться с поддержкой',
            error_404: '404 - Страница не найдена',
            error_500: '500 - Ошибка сервера',
            error_403: '403 - Доступ запрещен',
            error_419: '419 - Сессия истекла',
        },
        dashboard: {
            title: 'Панель управления',
            greeting_morning: 'Доброе утро',
            greeting_afternoon: 'Добрый день',
            greeting_evening: 'Добрый вечер',
            welcome_messages: [
                `Добро пожаловать в ${appName}. Давайте создадим что-то удивительное сегодня.`,
                'Готовы автоматизировать социальные сети? Начнём!',
                'Ваш контент заслуживает внимания. Давайте воплотим это в жизнь.',
                'Время превратить ваши идеи в увлекательные публикации.',
                'Отличный контент начинается здесь. Что вы создадите сегодня?',
                'Давайте вместе развивать ваше присутствие в Instagram.',
                'С возвращением! Ваша аудитория ждёт вашу следующую публикацию.',
            ],
            instagram_accounts: 'Аккаунты Instagram',
            scheduled_posts: 'Запланированные публикации',
            wallet_balance: 'Баланс кошелька',
            connect_instagram: 'Подключить Instagram',
            connect_instagram_desc:
                'Свяжите свой аккаунт Instagram, чтобы начать автоматизацию контента.',
            connect_now: 'Подключить сейчас',
            actions: {
                create_post: 'Создать публикацию',
                create_post_desc:
                    'Планируйте и публикуйте контент в ваших аккаунтах Instagram.',
                coming_soon: 'СКОРО',
            },
            empty_state: {
                no_posts: 'Пока нет публикаций',
                get_started: 'Начните с создания вашей первой публикации',
            },
            recent_posts: 'Недавние публикации',
            view_all_posts: 'Посмотреть все публикации',
        },
        posts: {
            create_post: 'Создать публикацию',
            back_to_posts: 'Назад к публикациям',
            select_post_type: 'Выберите тип публикации',
            select_post_type_description:
                'Выберите тип контента, который хотите создать',
            select_instagram_account: 'Выберите аккаунт Instagram',
            select_instagram_account_description:
                'Выберите, в какой аккаунт Instagram публиковать',
            select_account: 'Выбрать аккаунт',
            post_details: 'Детали публикации',
            title: 'Управление публикациями',
            optional: 'Необязательно',
            title_placeholder: 'Введите заголовок для вашей публикации...',
            caption: 'Подпись',
            caption_placeholder: 'Напишите подпись здесь...',
            characters: 'символов',
            status_label: 'Статус',
            type_label: 'Тип',
            media_upload: 'Загрузка медиа',
            media_upload_description:
                'Загрузите изображения или видео для вашей публикации',
            scheduling: 'Планирование',
            scheduling_description:
                'Выберите, когда опубликовать вашу публикацию',
            publish_immediately: 'Опубликовать сейчас',
            save_draft: 'Сохранить черновик',
            schedule_for_later: 'Запланировать на потом',
            cancel: 'Отмена',
            // Scheduling Interface
            quick_select: 'Быстрый выбор',
            custom_schedule: 'Настроить расписание',
            now: 'Сейчас',
            today_1h: 'Сегодня (+1 час)',
            today_3h: 'Сегодня (+3 часа)',
            today_6h: 'Сегодня (+6 часов)',
            tomorrow_9am: 'Завтра (9:00)',
            tomorrow_6pm: 'Завтра (18:00)',
            next_week: 'На следующей неделе',
            next_month: 'В следующем месяце',
            select_date: 'Выберите дату',
            select_time: 'Выберите время',
            date_placeholder: 'Выберите дату',
            time_placeholder: 'Выберите время',
            scheduled_for: 'Запланировано на',
            type: {
                feed: 'Публикация в ленте',
                feed_description:
                    'Обычная публикация, которая появляется в вашей ленте',
                reel: 'Reel',
                reel_description: 'Короткие видео',
                story: 'История',
                story_description:
                    'Временный контент, который исчезает через 24 часа',
                carousel: 'Карусель',
                carousel_description:
                    'Несколько изображений или видео в одной публикации',
            },
            media: {
                upload: 'Загрузить медиа',
                or_drag_drop: 'или перетащите файлы сюда',
                supported_formats:
                    'Поддерживаемые форматы: JPG, PNG, GIF, MP4, MOV',
                add_more: 'Добавить еще файлы',
                existing: 'Существующий',
                duplicated: 'Дублированный',
                too_many_files: 'Слишком много файлов. Максимум {max} файлов.',
                file_too_large:
                    'Файл {name} слишком большой. Максимальный размер {max}.',
                invalid_file_type: 'Файл {name} имеет недопустимый тип {type}.',
            },
            select_date: 'Выберите дату',
            select_time: 'Выберите время',
            date_placeholder: 'Выберите дату...',
            time_placeholder: 'Выберите время...',
            scheduled_for: 'Запланировано на',
            quick_select: 'Быстрый выбор',
            today_6pm: 'Сегодня 18:00',
            tomorrow_9am: 'Завтра 9:00',
            tomorrow_12pm: 'Завтра 12:00',
            tomorrow_6pm: 'Завтра 18:00',
            next_week: 'На следующей неделе',
            next_month: 'В следующем месяце',
            creating: 'Создание...',
            all_statuses: 'Все статусы',
            all_types: 'Все типы',
            search_posts: 'Поиск публикаций...',
            no_posts: 'Публикации не найдены',
            no_posts_description: 'Начните с создания вашей первой публикации',
            status: {
                draft: 'Черновик',
                scheduled: 'Запланировано',
                publishing: 'Публикация',
                published: 'Опубликовано',
                failed: 'Ошибка',
            },
            stats: {
                total_posts: 'Всего публикаций',
            },
            created_successfully: 'Публикация успешно создана!',
            view: 'Просмотр',
            edit: 'Редактировать',
            delete: 'Удалить',
            duplicate: 'Дублировать',
            actions: 'Действия',
            media_count: 'Медиа',
            source: 'Источник',
            created_at: 'Создано',
            scheduled_at: 'Запланировано',
            images: 'изображений',
            videos: 'видео',
            no_media: 'Нет медиа',
            unknown_source: 'Неизвестно',
            not_scheduled: 'Не запланировано',
            untitled: 'Без названия',
            no_caption: 'Без описания',
            confirm_delete: 'Вы уверены, что хотите удалить эту публикацию?',
            deleted_successfully: 'Публикация успешно удалена!',
            delete_failed: 'Не удалось удалить публикацию.',
            no_instagram_accounts: 'Нет подключенных аккаунтов Instagram',
            no_instagram_accounts_description:
                'Вам нужно подключить аккаунт Instagram перед созданием публикаций.',
            connect_instagram_account: 'Подключить аккаунт Instagram',
            assign_account_later: 'Вы можете назначить аккаунт Instagram позже',
            create_post_without_account:
                'Вы можете создать публикацию без подключения аккаунта Instagram',
            or: 'или',
            assign_later: 'назначить позже',
        },
        common: {
            view: 'Просмотр',
            edit: 'Редактировать',
            delete: 'Удалить',
            save: 'Сохранить',
            cancel: 'Отмена',
            back: 'Назад',
            next: 'Далее',
            previous: 'Предыдущий',
            loading: 'Загрузка...',
            error: 'Ошибка',
            success: 'Успешно',
            warning: 'Предупреждение',
            info: 'Информация',
            yes: 'Да',
            no: 'Нет',
            ok: 'ОК',
            close: 'Закрыть',
            open: 'Открыть',
            search: 'Поиск',
            filter: 'Фильтр',
            sort: 'Сортировка',
            refresh: 'Обновить',
            export: 'Экспорт',
            import: 'Импорт',
            download: 'Скачать',
            upload: 'Загрузить',
            select: 'Выбрать',
            select_all: 'Выбрать все',
            deselect_all: 'Снять выделение',
            clear: 'Очистить',
            reset: 'Сбросить',
            submit: 'Отправить',
            confirm: 'Подтвердить',
            optional: 'Необязательно',
            required: 'Обязательно',
        },
        menu: {
            dashboard: 'Панель управления',
            posts: 'Публикации',
            company: 'Компания',
            create_company: 'Создать Компанию',
            profile: 'Профиль',
            logout: 'Выйти',
            instagram: 'Instagram',
            instagram_accounts: 'Аккаунты Instagram',
            admin: 'Администрирование',
            inquiries: 'Запросы',
            users: 'Пользователи',
        },
        theme: {
            switchToDark: 'Переключить на темную тему',
            switchToLight: 'Переключить на светлую тему',
        },
        instagram: {
            title: 'Аккаунты Instagram',
            no_accounts: 'Аккаунты Instagram еще не подключены',
            connect_description:
                'Подключите свой аккаунт Instagram, чтобы начать автоматизацию публикации контента.',
            connect_button: 'Подключить аккаунт Instagram',
            not_configured:
                'Интеграция с Instagram еще не настроена. Пожалуйста, свяжитесь с администратором для настройки учетных данных Instagram API.',
            no_active_company:
                'Для подключения аккаунтов Instagram необходима активная компания. Пожалуйста, создайте или выберите компанию.',
            connected: 'Подключен',
            sync: 'Синхронизировать',
            disconnect: 'Отключить',
            disconnect_confirm:
                'Вы уверены, что хотите отключить @{username}? Вы можете переподключить его в любое время.',
            disconnect_confirm_title: 'Отключить аккаунт Instagram?',
            disconnect_confirm_message:
                'Вы уверены, что хотите отключить {username}? Вы можете переподключить его в любое время.',
            disconnect_button: 'Да, отключить',
            disconnect_cancel: 'Отмена',
            status_active: 'Активен',
            status_expired: 'Истек',
            status_expiring_soon: 'Скоро истечет',
            token_warning:
                'Ваш токен доступа скоро истечет. Пожалуйста, переподключите этот аккаунт для продолжения публикаций.',
        },
        company: {
            title: 'Информация о компании',
            description: 'Детали вашей текущей компании и команды.',
            no_company: 'В настоящее время вы не связаны ни с одной компанией.',
            member_since: 'Участник с',
            role_admin: 'Администратор',
            role_user: 'Пользователь',
            role_network: 'Администратор компании',
            member_singular: 'Участник команды',
            member_plural: 'Участники команды',
            instagram_account_singular: 'Аккаунт Instagram',
            instagram_account_plural: 'Аккаунты Instagram',
            manage_accounts: 'Управление аккаунтами Instagram',
            create: {
                title: 'Создать компанию',
                heading: 'Создайте свою компанию',
                description:
                    'Настройте свою компанию для начала сотрудничества с командой.',
                name_label: 'Название компании',
                name_placeholder: 'Введите название вашей компании',
                info_title: 'Что происходит дальше?',
                info_1: 'Вы станете администратором компании',
                info_2: 'Вы можете пригласить участников команды присоединиться',
                info_3: 'Все публикации будут связаны с вашей компанией',
                create_button: 'Создать компанию',
                creating: 'Создание...',
            },
            settings: {
                title: 'Настройки компании',
                company_info: 'Информация о компании',
                company_name: 'Название компании',
                created_at: 'Создано',
                team_members: 'Участники команды',
                invite_member: 'Пригласить участника',
                member: 'Участник',
                role: 'Роль',
                joined: 'Присоединился',
                actions: 'Действия',
                owner: 'Владелец',
                role_admin: 'Администратор',
                role_user: 'Пользователь',
                role_network: 'Администратор компании',
                edit_role: 'Изменить роль',
                remove: 'Удалить',
                pending_invitations: 'Ожидающие приглашения',
                email: 'Электронная почта',
                invited_by: 'Приглашен',
                expires: 'Истекает',
                resend_invitation: 'Повторно отправить приглашение',
                cancel: 'Отмена',
                update_role: 'Обновить роль',
                update_role_description: 'Обновить роль для {name}',
                update: 'Обновить',
                invite_new_member: 'Пригласить нового участника',
                invite_description:
                    'Отправить приглашение присоединиться к команде вашей компании.',
                email_placeholder: 'Введите адрес электронной почты',
                send_invitation: 'Отправить приглашение',
                confirm_remove_user:
                    'Вы уверены, что хотите удалить {name} из компании?',
                confirm_cancel_invitation:
                    'Вы уверены, что хотите отменить приглашение для {email}?',
            },
            invitation: {
                sent: 'Приглашение отправлено на {email}',
                resent: 'Приглашение повторно отправлено успешно',
                cancelled: 'Приглашение отменено успешно',
                cannot_resend_accepted:
                    'Нельзя повторно отправить принятое приглашение.',
            },
            toast: {
                need_company_first: 'Сначала нужно создать компанию.',
                no_permission:
                    'У вас нет разрешения на выполнение этого действия.',
                role_updated: 'Роль пользователя обновлена успешно',
                user_removed: 'Пользователь удален из компании успешно',
                login_required:
                    'Пожалуйста, войдите в систему, чтобы принять приглашение.',
                accepted:
                    'Добро пожаловать в компанию! Теперь вы можете получить доступ ко всем функциям компании.',
            },
        },
        profile: {
            title: 'Профиль',
            information: {
                title: 'Информация профиля',
                description:
                    'Обновите информацию вашего профиля и адрес электронной почты.',
                name: 'Имя',
                email: 'Электронная почта',
                timezone: 'Часовой пояс',
                timezone_description:
                    'Все даты и время будут отображаться в выбранном часовом поясе.',
                search_timezone: 'Поиск часовых поясов...',
                common_timezones:
                    '🌟 Быстрый выбор (США, Канада и Ключевые города)',
                all_timezones: '🌍 Все часовые пояса',
                unverified_email: 'Ваш адрес электронной почты не подтвержден.',
                resend_verification:
                    'Нажмите здесь, чтобы повторно отправить письмо с подтверждением.',
                verification_sent:
                    'Новая ссылка для подтверждения отправлена на ваш адрес электронной почты.',
                save: 'Сохранить',
                saved: 'Сохранено.',
            },
            password: {
                title: 'Обновить пароль',
                description:
                    'Убедитесь, что ваша учетная запись использует длинный случайный пароль для обеспечения безопасности.',
                current_password: 'Текущий пароль',
                new_password: 'Новый пароль',
                confirm_password: 'Подтвердите пароль',
                save: 'Сохранить',
                saved: 'Сохранено.',
            },
            delete: {
                title: 'Удалить аккаунт',
                description:
                    'После удаления вашей учетной записи все ее ресурсы и данные будут удалены навсегда. Перед удалением учетной записи загрузите все данные или информацию, которую хотите сохранить.',
                button: 'Удалить аккаунт',
                confirm_title:
                    'Вы уверены, что хотите удалить свою учетную запись?',
                confirm_description:
                    'После удаления вашей учетной записи все ее ресурсы и данные будут удалены навсегда. Пожалуйста, введите свой пароль для подтверждения окончательного удаления учетной записи.',
                password: 'Пароль',
                password_placeholder: 'Пароль',
                cancel: 'Отмена',
                confirm_button: 'Удалить аккаунт',
            },
            company: {
                title: 'Информация о компании',
                description: 'Детали вашей текущей компании и команды.',
                member_since: 'Участник с',
                role_admin: 'Администратор',
                role_user: 'Пользователь',
                role_network: 'Администратор компании',
                member_singular: 'Участник команды',
                member_plural: 'Участники команды',
                instagram_account_singular: 'Аккаунт Instagram',
                instagram_account_plural: 'Аккаунты Instagram',
                manage_accounts: 'Управление аккаунтами Instagram',
            },
        },
        timezone: {
            your_timezone: 'Ваш часовой пояс',
            current_time: 'Текущее время',
            click_to_change: 'Нажмите, чтобы изменить часовой пояс',
            timezone: 'Часовой пояс',
            local_time: 'Местное время',
        },
        admin: {
            inquiries: {
                title: 'Управление Запросами',
                email: 'Электронная почта',
                ip_address: 'IP-адрес',
                user_agent: 'User Agent',
                created_at: 'Создано',
                delete: 'Удалить',
                export: 'Экспорт CSV',
                export_button: 'Экспортировать в CSV',
                search: 'Поиск по email...',
                search_placeholder: 'Поиск запросов...',
                no_results: 'Запросы не найдены',
                total: 'Всего Запросов',
                today: 'Сегодня',
                this_week: 'На Этой Неделе',
                this_month: 'В Этом Месяце',
                delete_confirm_title: 'Удалить Запрос?',
                delete_confirm_message:
                    'Это действие нельзя отменить. Запрос будет удалён навсегда.',
                confirm_delete: 'Да, удалить',
                cancel: 'Отмена',
                deleted_success: 'Удалено!',
                deleted_message: 'Запрос успешно удалён.',
                delete_error: 'Ошибка!',
                delete_error_message:
                    'Не удалось удалить запрос. Попробуйте снова.',
                tooltip_total: 'Общее количество полученных запросов',
                tooltip_today: 'Запросы, полученные сегодня',
                tooltip_this_week: 'Запросы, полученные на этой неделе',
                tooltip_this_month: 'Запросы, полученные в этом месяце',
            },
            users: {
                title: 'Управление Пользователями',
                name: 'Имя',
                email: 'Электронная почта',
                role: 'Роль',
                status: 'Статус',
                last_login: 'Последний Вход',
                stats: 'Статистика',
                actions: 'Действия',
                search: 'Поиск пользователей...',
                search_placeholder: 'Поиск по имени или email...',
                no_results: 'Пользователи не найдены',
                total_users: 'Всего Пользователей',
                active_users: 'Активные',
                suspended_users: 'Заблокированные',
                new_this_month: 'Новых в Этом Месяце',
                send_password_reset: 'Отправить Ссылку на Сброс Пароля',
                suspend: 'Заблокировать Пользователя',
                unsuspend: 'Разблокировать Пользователя',
                impersonate: 'Войти как Пользователь',
                active: 'Активен',
                suspended: 'Заблокирован',
                suspension_reason: 'Причина',
                never_logged_in: 'Никогда не входил',
                companies_count: 'Компании',
                instagram_accounts: 'Аккаунты Instagram',
                posts_count: 'Публикации',
                suspend_modal_title: 'Блокировка Пользователя',
                suspend_modal_message:
                    'Пожалуйста, укажите причину блокировки:',
                confirm_suspend: 'Заблокировать',
                cancel: 'Отмена',
                confirm_impersonate_title: 'Вход как Пользователь',
                confirm_impersonate_message:
                    'Вы войдёте как этот пользователь. Вы можете остановить вход в любое время.',
                confirm_password_reset_title: 'Отправить Сброс Пароля?',
                confirm_password_reset_message:
                    'Ссылка для сброса пароля будет отправлена на',
                confirm_unsuspend_title: 'Разблокировать Пользователя?',
                confirm_unsuspend_message:
                    'Этот пользователь снова сможет войти в систему.',
                confirm: 'Подтвердить',
                success: 'Успешно!',
                error: 'Ошибка!',
                password_reset_sent:
                    'Ссылка для сброса пароля успешно отправлена',
                user_suspended: 'Пользователь заблокирован',
                user_unsuspended: 'Пользователь разблокирован',
                impersonation_started: 'Теперь вы работаете как пользователь',
                action_failed:
                    'Не удалось выполнить действие. Попробуйте снова.',
                tooltip_total_users:
                    'Общее количество зарегистрированных пользователей',
                tooltip_active_users:
                    'Пользователи, которые активны и не заблокированы',
                tooltip_suspended_users:
                    'Пользователи, которые были заблокированы администраторами',
                tooltip_new_this_month:
                    'Новые пользователи, зарегистрированные в этом месяце',
            },
            impersonating: 'Вы вошли как',
            stop_impersonation: 'Остановить Вход',
            loading: 'Загрузка...',
        },
    },
    es: {
        auth: {
            email: 'Correo electrónico',
            enter_email: 'Ingrese su correo electrónico',
            continue: 'Continuar',
            welcome_back: '¡Bienvenido de nuevo!',
            new_here: '¿Nuevo aquí? Crearemos tu cuenta.',
            login: 'Iniciar sesión',
            register: 'Registrarse',
            password: 'Contraseña',
            remember_me: 'Recuérdame',
            forgot_password: '¿Olvidaste tu contraseña?',
            secure_auth: `Autenticación segura con ${appName}`,
            forgot_password_title: 'Olvidé mi contraseña',
            forgot_password_description:
                '¿Olvidaste tu contraseña? No hay problema.\nIngresa tu email a continuación, y te enviaremos un enlace para restablecerla de forma segura.',
            email_password_reset_link: 'Enviar enlace de restablecimiento',
            reset: 'Restablecer',
            back: 'Atrás',
            back_to_login: 'Volver al inicio de sesión',
            remember_password: '¿Recuerdas tu contraseña?',
        },
        errors: {
            page_not_found: 'Página no encontrada',
            page_not_found_description:
                'Lo sentimos, la página que buscas no se pudo encontrar.',
            server_error: 'Error del servidor',
            server_error_description:
                'Algo salió mal de nuestro lado. Por favor, inténtalo de nuevo más tarde.',
            forbidden: 'Acceso prohibido',
            forbidden_description:
                'No tienes permisos para acceder a este recurso.',
            csrf_mismatch: 'Sesión expirada',
            csrf_mismatch_description:
                'Tu sesión ha expirado. Por favor, actualiza la página e inténtalo de nuevo.',
            go_home: 'Ir al inicio',
            try_again: 'Intentar de nuevo',
            go_back: 'Volver',
            refresh_page: 'Actualizar página',
            need_help:
                '¿Necesitas ayuda? Contacta a nuestro equipo de soporte.',
            contact_support: 'Contactar soporte',
            error_404: '404 - Página no encontrada',
            error_500: '500 - Error del servidor',
            error_403: '403 - Acceso prohibido',
            error_419: '419 - Sesión expirada',
        },
        dashboard: {
            title: 'Panel de control',
            greeting_morning: 'Buenos días',
            greeting_afternoon: 'Buenas tardes',
            greeting_evening: 'Buenas noches',
            welcome_messages: [
                `Bienvenido a ${appName}. Hagamos algo increíble hoy.`,
                '¿Listo para automatizar tus redes sociales? ¡Comencemos!',
                'Tu contenido merece brillar. Hagámoslo realidad.',
                'Es hora de convertir tus ideas en publicaciones atractivas.',
                'El gran contenido comienza aquí. ¿Qué crearás hoy?',
                'Crezcamos juntos tu presencia en Instagram.',
                '¡Bienvenido de nuevo! Tu audiencia espera tu próxima publicación.',
            ],
            instagram_accounts: 'Cuentas de Instagram',
            scheduled_posts: 'Publicaciones programadas',
            wallet_balance: 'Saldo de la cartera',
            connect_instagram: 'Conectar Instagram',
            connect_instagram_desc:
                'Vincula tu cuenta de Instagram para comenzar a automatizar tu contenido.',
            connect_now: 'Conectar ahora',
            actions: {
                create_post: 'Crear publicación',
                create_post_desc:
                    'Programa y publica contenido en tus cuentas de Instagram.',
                coming_soon: 'PRÓXIMAMENTE',
            },
            empty_state: {
                no_posts: 'Aún no hay publicaciones',
                get_started: 'Comienza creando tu primera publicación',
            },
            recent_posts: 'Publicaciones Recientes',
            view_all_posts: 'Ver todas las publicaciones',
        },
        posts: {
            create_post: 'Crear publicación',
            back_to_posts: 'Volver a publicaciones',
            select_post_type: 'Seleccionar tipo de publicación',
            select_post_type_description:
                'Elige el tipo de contenido que quieres crear',
            select_instagram_account: 'Seleccionar cuenta de Instagram',
            select_instagram_account_description:
                'Elige a qué cuenta de Instagram publicar',
            select_account: 'Seleccionar cuenta',
            post_details: 'Detalles de la publicación',
            title: 'Gestión de publicaciones',
            optional: 'Opcional',
            title_placeholder: 'Ingresa un título para tu publicación...',
            caption: 'Descripción',
            caption_placeholder: 'Escribe tu descripción aquí...',
            characters: 'caracteres',
            status_label: 'Estado',
            type_label: 'Tipo',
            media_upload: 'Subir medios',
            media_upload_description:
                'Sube imágenes o videos para tu publicación',
            scheduling: 'Programación',
            scheduling_description: 'Elige cuándo publicar tu contenido',
            publish_immediately: 'Publicar ahora',
            save_draft: 'Guardar borrador',
            schedule_for_later: 'Programar para después',
            cancel: 'Cancelar',
            // Scheduling Interface
            quick_select: 'Selección rápida',
            custom_schedule: 'Programación personalizada',
            now: 'Ahora',
            today_1h: 'Hoy (+1 hora)',
            today_3h: 'Hoy (+3 horas)',
            today_6h: 'Hoy (+6 horas)',
            tomorrow_9am: 'Mañana (9:00 AM)',
            tomorrow_6pm: 'Mañana (6:00 PM)',
            next_week: 'La próxima semana',
            next_month: 'El próximo mes',
            select_date: 'Seleccionar fecha',
            select_time: 'Seleccionar hora',
            date_placeholder: 'Elige una fecha',
            time_placeholder: 'Elige una hora',
            scheduled_for: 'Programado para',
            type: {
                feed: 'Publicación en feed',
                feed_description: 'Publicación regular que aparece en tu feed',
                reel: 'Reel',
                reel_description: 'Contenido de video corto',
                story: 'Historia',
                story_description:
                    'Contenido temporal que desaparece después de 24 horas',
                carousel: 'Carrusel',
                carousel_description:
                    'Múltiples imágenes o videos en una publicación',
            },
            media: {
                upload: 'Subir medios',
                or_drag_drop: 'o arrastra y suelta archivos aquí',
                supported_formats:
                    'Formatos soportados: JPG, PNG, GIF, MP4, MOV',
                add_more: 'Agregar más archivos',
                existing: 'Existente',
                duplicated: 'Duplicado',
                too_many_files:
                    'Demasiados archivos. Máximo {max} archivos permitidos.',
                file_too_large:
                    'El archivo {name} es demasiado grande. Tamaño máximo {max}.',
                invalid_file_type:
                    'El archivo {name} tiene un tipo inválido {type}.',
            },
            select_date: 'Seleccionar fecha',
            select_time: 'Seleccionar hora',
            date_placeholder: 'Elige una fecha...',
            time_placeholder: 'Elige una hora...',
            scheduled_for: 'Programado para',
            quick_select: 'Selección rápida',
            today_6pm: 'Hoy 6:00 PM',
            tomorrow_9am: 'Mañana 9:00 AM',
            tomorrow_12pm: 'Mañana 12:00 PM',
            tomorrow_6pm: 'Mañana 6:00 PM',
            next_week: 'Próxima semana',
            next_month: 'Próximo mes',
            creating: 'Creando...',
            all_statuses: 'Todos los estados',
            all_types: 'Todos los tipos',
            search_posts: 'Buscar publicaciones...',
            no_posts: 'No se encontraron publicaciones',
            no_posts_description: 'Comienza creando tu primera publicación',
            status: {
                draft: 'Borrador',
                scheduled: 'Programado',
                publishing: 'Publicando',
                published: 'Publicado',
                failed: 'Fallido',
            },
            stats: {
                total_posts: 'Total de Publicaciones',
            },
            created_successfully: '¡Publicación creada exitosamente!',
            view: 'Ver',
            edit: 'Editar',
            delete: 'Eliminar',
            duplicate: 'Duplicar',
            actions: 'Acciones',
            media_count: 'Medios',
            source: 'Fuente',
            created_at: 'Creado',
            scheduled_at: 'Programado',
            images: 'imágenes',
            videos: 'videos',
            no_media: 'Sin medios',
            unknown_source: 'Desconocido',
            not_scheduled: 'No programado',
            untitled: 'Sin título',
            no_caption: 'Sin descripción',
            confirm_delete:
                '¿Estás seguro de que quieres eliminar esta publicación?',
            deleted_successfully: '¡Publicación eliminada exitosamente!',
            delete_failed: 'Error al eliminar la publicación.',
            no_instagram_accounts: 'No hay cuentas de Instagram conectadas',
            no_instagram_accounts_description:
                'Necesitas conectar una cuenta de Instagram antes de crear publicaciones.',
            connect_instagram_account: 'Conectar cuenta de Instagram',
            assign_account_later:
                'Puedes asignar una cuenta de Instagram más tarde',
            create_post_without_account:
                'Puedes crear una publicación sin conectar una cuenta de Instagram primero',
            or: 'o',
            assign_later: 'asignar más tarde',
        },
        common: {
            view: 'Ver',
            edit: 'Editar',
            delete: 'Eliminar',
            save: 'Guardar',
            cancel: 'Cancelar',
            back: 'Atrás',
            next: 'Siguiente',
            previous: 'Anterior',
            loading: 'Cargando...',
            error: 'Error',
            success: 'Éxito',
            warning: 'Advertencia',
            info: 'Información',
            yes: 'Sí',
            no: 'No',
            ok: 'OK',
            close: 'Cerrar',
            open: 'Abrir',
            search: 'Buscar',
            filter: 'Filtrar',
            sort: 'Ordenar',
            refresh: 'Actualizar',
            export: 'Exportar',
            import: 'Importar',
            download: 'Descargar',
            upload: 'Subir',
            select: 'Seleccionar',
            select_all: 'Seleccionar todo',
            deselect_all: 'Deseleccionar todo',
            clear: 'Limpiar',
            reset: 'Restablecer',
            submit: 'Enviar',
            confirm: 'Confirmar',
            optional: 'Opcional',
            required: 'Requerido',
        },
        menu: {
            dashboard: 'Panel de control',
            posts: 'Publicaciones',
            company: 'Empresa',
            create_company: 'Crear Empresa',
            profile: 'Perfil',
            logout: 'Cerrar sesión',
            instagram: 'Instagram',
            instagram_accounts: 'Cuentas de Instagram',
            admin: 'Administración',
            inquiries: 'Consultas',
            users: 'Usuarios',
        },
        theme: {
            switchToDark: 'Cambiar a modo oscuro',
            switchToLight: 'Cambiar a modo claro',
        },
        instagram: {
            title: 'Cuentas de Instagram',
            no_accounts: 'Aún no hay cuentas de Instagram conectadas',
            connect_description:
                'Conecta tu cuenta de Instagram para comenzar a automatizar la publicación de contenido.',
            connect_button: 'Conectar cuenta de Instagram',
            not_configured:
                'La integración con Instagram aún no está configurada. Por favor, contacta con tu administrador para configurar las credenciales de la API de Instagram.',
            no_active_company:
                'Necesitas tener una empresa activa para conectar cuentas de Instagram. Por favor, crea o selecciona una empresa primero.',
            connected: 'Conectado',
            sync: 'Sincronizar',
            disconnect: 'Desconectar',
            disconnect_confirm:
                '¿Estás seguro de que quieres desconectar @{username}? Puedes reconectarlo en cualquier momento.',
            disconnect_confirm_title: '¿Desconectar cuenta de Instagram?',
            disconnect_confirm_message:
                '¿Estás seguro de que quieres desconectar {username}? Puedes reconectarla en cualquier momento.',
            disconnect_button: 'Sí, desconectar',
            disconnect_cancel: 'Cancelar',
            status_active: 'Activo',
            status_expired: 'Expirado',
            status_expiring_soon: 'Por expirar',
            token_warning:
                'Tu token de acceso expirará pronto. Por favor, vuelve a conectar esta cuenta para continuar publicando.',
        },
        company: {
            title: 'Información de la Empresa',
            description: 'Detalles de tu empresa actual y equipo.',
            no_company: 'Actualmente no estás asociado con ninguna empresa.',
            member_since: 'Miembro desde',
            role_admin: 'Administrador',
            role_user: 'Usuario',
            role_network: 'Administrador de Empresa',
            member_singular: 'Miembro del Equipo',
            member_plural: 'Miembros del Equipo',
            instagram_account_singular: 'Cuenta de Instagram',
            instagram_account_plural: 'Cuentas de Instagram',
            manage_accounts: 'Gestionar Cuentas de Instagram',
            create: {
                title: 'Crear Empresa',
                heading: 'Crea tu Empresa',
                description:
                    'Configura tu empresa para comenzar a colaborar con tu equipo.',
                name_label: 'Nombre de la Empresa',
                name_placeholder: 'Ingresa el nombre de tu empresa',
                info_title: '¿Qué sucede después?',
                info_1: 'Te convertirás en el administrador de la empresa',
                info_2: 'Puedes invitar miembros del equipo a unirse',
                info_3: 'Todas las publicaciones estarán asociadas con tu empresa',
                create_button: 'Crear Empresa',
                creating: 'Creando...',
            },
            settings: {
                title: 'Configuración de la Empresa',
                company_info: 'Información de la Empresa',
                company_name: 'Nombre de la Empresa',
                created_at: 'Creado el',
                team_members: 'Miembros del Equipo',
                invite_member: 'Invitar Miembro',
                member: 'Miembro',
                role: 'Rol',
                joined: 'Se unió',
                actions: 'Acciones',
                owner: 'Propietario',
                role_admin: 'Administrador',
                role_user: 'Usuario',
                role_network: 'Administrador de Empresa',
                edit_role: 'Editar Rol',
                remove: 'Eliminar',
                pending_invitations: 'Invitaciones Pendientes',
                email: 'Correo Electrónico',
                invited_by: 'Invitado por',
                expires: 'Expira',
                resend_invitation: 'Reenviar Invitación',
                cancel: 'Cancelar',
                update_role: 'Actualizar Rol',
                update_role_description: 'Actualizar rol para {name}',
                update: 'Actualizar',
                invite_new_member: 'Invitar Nuevo Miembro',
                invite_description:
                    'Enviar una invitación para unirse al equipo de tu empresa.',
                email_placeholder: 'Ingresa dirección de correo electrónico',
                send_invitation: 'Enviar Invitación',
                confirm_remove_user:
                    '¿Estás seguro de que quieres eliminar {name} de la empresa?',
                confirm_cancel_invitation:
                    '¿Estás seguro de que quieres cancelar la invitación a {email}?',
            },
            invitation: {
                sent: 'Invitación enviada a {email}',
                resent: 'Invitación reenviada exitosamente',
                cancelled: 'Invitación cancelada exitosamente',
                cannot_resend_accepted:
                    'No se puede reenviar una invitación aceptada.',
            },
            toast: {
                need_company_first: 'Necesitas crear una empresa primero.',
                no_permission: 'No tienes permisos para realizar esta acción.',
                role_updated: 'Rol de usuario actualizado exitosamente',
                user_removed: 'Usuario eliminado de la empresa exitosamente',
                login_required:
                    'Por favor, inicia sesión para aceptar la invitación.',
                accepted:
                    '¡Bienvenido a la empresa! Ahora puedes acceder a todas las funciones de la empresa.',
            },
        },
        profile: {
            title: 'Perfil',
            information: {
                title: 'Información del Perfil',
                description:
                    'Actualiza la información de tu cuenta y dirección de correo electrónico.',
                name: 'Nombre',
                email: 'Correo Electrónico',
                timezone: 'Zona Horaria',
                timezone_description:
                    'Todas las fechas y horas se mostrarán en la zona horaria seleccionada.',
                search_timezone: 'Buscar zonas horarias...',
                common_timezones:
                    '🌟 Selección Rápida (EE.UU., Canadá y Ciudades Clave)',
                all_timezones: '🌍 Todas las Zonas Horarias',
                unverified_email:
                    'Tu dirección de correo electrónico no está verificada.',
                resend_verification:
                    'Haz clic aquí para reenviar el correo de verificación.',
                verification_sent:
                    'Se ha enviado un nuevo enlace de verificación a tu dirección de correo electrónico.',
                save: 'Guardar',
                saved: 'Guardado.',
            },
            password: {
                title: 'Actualizar Contraseña',
                description:
                    'Asegúrate de que tu cuenta utiliza una contraseña larga y aleatoria para mantener la seguridad.',
                current_password: 'Contraseña Actual',
                new_password: 'Nueva Contraseña',
                confirm_password: 'Confirmar Contraseña',
                save: 'Guardar',
                saved: 'Guardado.',
            },
            delete: {
                title: 'Eliminar Cuenta',
                description:
                    'Una vez que se elimine tu cuenta, todos sus recursos y datos se eliminarán permanentemente. Antes de eliminar tu cuenta, descarga cualquier dato o información que desees conservar.',
                button: 'Eliminar Cuenta',
                confirm_title:
                    '¿Estás seguro de que quieres eliminar tu cuenta?',
                confirm_description:
                    'Una vez que se elimine tu cuenta, todos sus recursos y datos se eliminarán permanentemente. Por favor, ingresa tu contraseña para confirmar que deseas eliminar permanentemente tu cuenta.',
                password: 'Contraseña',
                password_placeholder: 'Contraseña',
                cancel: 'Cancelar',
                confirm_button: 'Eliminar Cuenta',
            },
            company: {
                title: 'Información de la Empresa',
                description: 'Detalles de tu empresa actual y equipo.',
                member_since: 'Miembro desde',
                role_admin: 'Administrador',
                role_user: 'Usuario',
                role_network: 'Administrador de Empresa',
                member_singular: 'Miembro del Equipo',
                member_plural: 'Miembros del Equipo',
                instagram_account_singular: 'Cuenta de Instagram',
                instagram_account_plural: 'Cuentas de Instagram',
                manage_accounts: 'Gestionar Cuentas de Instagram',
            },
        },
        timezone: {
            your_timezone: 'Tu Zona Horaria',
            current_time: 'Hora Actual',
            click_to_change: 'Haz clic para cambiar la zona horaria',
            timezone: 'Zona Horaria',
            local_time: 'Hora Local',
        },
        admin: {
            inquiries: {
                title: 'Gestión de Consultas',
                email: 'Correo electrónico',
                ip_address: 'Dirección IP',
                user_agent: 'Agente de Usuario',
                created_at: 'Creado el',
                delete: 'Eliminar',
                export: 'Exportar CSV',
                export_button: 'Exportar a CSV',
                search: 'Buscar por correo...',
                search_placeholder: 'Buscar consultas...',
                no_results: 'No se encontraron consultas',
                total: 'Total de Consultas',
                today: 'Hoy',
                this_week: 'Esta Semana',
                this_month: 'Este Mes',
                delete_confirm_title: '¿Eliminar Consulta?',
                delete_confirm_message:
                    'Esta acción no se puede deshacer. La consulta se eliminará permanentemente.',
                confirm_delete: 'Sí, eliminarla',
                cancel: 'Cancelar',
                deleted_success: '¡Eliminado!',
                deleted_message: 'La consulta se ha eliminado correctamente.',
                delete_error: '¡Error!',
                delete_error_message:
                    'No se pudo eliminar la consulta. Por favor, inténtelo de nuevo.',
                tooltip_total: 'Número total de consultas recibidas',
                tooltip_today: 'Consultas recibidas hoy',
                tooltip_this_week: 'Consultas recibidas esta semana',
                tooltip_this_month: 'Consultas recibidas este mes',
            },
            users: {
                title: 'Gestión de Usuarios',
                name: 'Nombre',
                email: 'Correo electrónico',
                role: 'Rol',
                status: 'Estado',
                last_login: 'Último Acceso',
                stats: 'Estadísticas',
                actions: 'Acciones',
                search: 'Buscar usuarios...',
                search_placeholder: 'Buscar por nombre o correo...',
                no_results: 'No se encontraron usuarios',
                total_users: 'Total de Usuarios',
                active_users: 'Activos',
                suspended_users: 'Suspendidos',
                new_this_month: 'Nuevos Este Mes',
                send_password_reset: 'Enviar Restablecimiento de Contraseña',
                suspend: 'Suspender Usuario',
                unsuspend: 'Reactivar Usuario',
                impersonate: 'Suplantar',
                active: 'Activo',
                suspended: 'Suspendido',
                suspension_reason: 'Razón',
                never_logged_in: 'Nunca ha iniciado sesión',
                companies_count: 'Empresas',
                instagram_accounts: 'Cuentas de Instagram',
                posts_count: 'Publicaciones',
                suspend_modal_title: 'Suspender Usuario',
                suspend_modal_message:
                    'Por favor, proporcione una razón para la suspensión:',
                confirm_suspend: 'Suspender',
                cancel: 'Cancelar',
                confirm_impersonate_title: 'Suplantar Usuario',
                confirm_impersonate_message:
                    'Iniciará sesión como este usuario. Puede detener la suplantación en cualquier momento.',
                confirm_password_reset_title:
                    '¿Enviar Restablecimiento de Contraseña?',
                confirm_password_reset_message:
                    'Se enviará un enlace de restablecimiento de contraseña a',
                confirm_unsuspend_title: '¿Reactivar Usuario?',
                confirm_unsuspend_message:
                    'Este usuario podrá iniciar sesión nuevamente.',
                confirm: 'Confirmar',
                success: '¡Éxito!',
                error: '¡Error!',
                password_reset_sent:
                    'Enlace de restablecimiento de contraseña enviado correctamente',
                user_suspended: 'Usuario suspendido',
                user_unsuspended: 'Usuario reactivado',
                impersonation_started: 'Ahora está suplantando al usuario',
                action_failed:
                    'No se pudo completar la acción. Por favor, inténtelo de nuevo.',
                tooltip_total_users: 'Número total de usuarios registrados',
                tooltip_active_users:
                    'Usuarios que están activos y no suspendidos',
                tooltip_suspended_users:
                    'Usuarios que han sido suspendidos por administradores',
                tooltip_new_this_month: 'Nuevos usuarios registrados este mes',
            },
            impersonating: 'Está suplantando a',
            stop_impersonation: 'Detener Suplantación',
            loading: 'Cargando...',
        },
    },
}

// Get locale (will be updated from Inertia page props)
const getInitialLocale = () => {
    // Try URL first
    const path = window.location.pathname
    const urlLocale = path.split('/')[1]
    if (['en', 'ru', 'es'].includes(urlLocale)) {
        return urlLocale
    }
    // Force English for testing
    return 'en'
}

const i18n = createI18n({
    legacy: false,
    locale: getInitialLocale(),
    fallbackLocale: 'en',
    messages,
})

createInertiaApp({
    title: (title) => `${title} - ${appName}`,
    resolve: (name) =>
        resolvePageComponent(
            `./Pages/${name}.vue`,
            import.meta.glob('./Pages/**/*.vue')
        ),
    setup({ el, App, props, plugin }) {
        const app = createApp({ render: () => h(App, props) })
            .use(plugin)
            .use(ZiggyVue)
            .use(i18n)

        // Sync i18n locale with Inertia page props
        if (props.initialPage?.props?.locale) {
            i18n.global.locale.value = props.initialPage.props.locale
        }

        // Global toast handling
        if (props.initialPage?.props?.toast) {
            // Import toast composable dynamically
            import('./composables/useToast.js').then(({ useToast }) => {
                const toast = useToast()
                toast.addToast(
                    props.initialPage.props.toast.message,
                    props.initialPage.props.toast.type || 'success'
                )
            })
        }

        return app.mount(el)
    },
    progress: {
        color: '#4B5563',
    },
})
